---
title: "Untitled"
output: html_document
# redirect output to another folder (default is base_dir/output)
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = fs::path(here::here(), "output"),
      ...
    )
  })
---

```{r setup, include=FALSE}
library(targets)
knitr::opts_chunk$set(echo = TRUE, tar_interactive = FALSE)
targets::tar_unscript()
# targets::tar_destroy()
```

```{targets set-globals, tar_globals=TRUE, include=FALSE}
future::plan(future.callr::callr)
search_games_mem <- memoise::memoise(
  tarflow.iquizoo::search_games,
  cache = cachem::cache_disk("~/.cache.tarflow")
)
games <- search_games_mem(config_where = config::get("where"))
# download recordings
url_path <- "https://static.cdn.iquizoo.com/eval3.x/pro/content/evaluationgame/MovieRecallTask"
out_path <- "recordings"
download_detail <- function(detail, ...) {
  curl::curl_download(fs::path(url_path, detail), fs::path(out_path, detail))
}
tar_option_set(
  package = c("tidyverse", "preproc.iquizoo", "tarflow.iquizoo"),
  format = "qs",
  imports = "preproc.iquizoo"
)
targets_data <- tarchetypes::tar_map(
  values = games,
  names = game_name_abbr,
  # major targets
  # tar_target(scores, pickup(query_tmpl_scores, config_where_single_game)),
  tar_target(data, pickup(query_tmpl_data, config_where_single_game)),
  tar_target(data_parsed, wrangle_data(data)),
  # tar_target(
  #   indices,
  #   preproc_data(data_parsed, prep_fun, .input = input, .extra = extra)
  # ),
  # configurations
  tar_target(
    config_where_single_game,
    insert_where_single_game(config_where, game_id)
  )
)
```

```{targets load-config, include=FALSE}
list(
  tar_target(file_config, "config.yml", format = "file"),
  tar_target(config_where, config::get("where", file = file_config))
)
```

```{targets download-users, include=FALSE}
list(
  tar_target(query_tmpl_users, fs::path("sql", "users.tmpl.sql"), format = "file"),
  tar_target(users, tarflow.iquizoo::pickup(query_tmpl_users, config_where))
)
```

```{targets data-and-scores, include=FALSE}
list(
  tar_target(query_tmpl_scores, fs::path("sql", "scores.tmpl.sql"), format = "file"),
  tar_target(query_tmpl_data, fs::path("sql", "data.tmpl.sql"), format = "file"),
  targets_data,
  tar_target(
    questions,
    tarflow.iquizoo::pickup(
      "
SELECT *
FROM iquizoo_content_db.question
  "
    )
  ),
  tar_target(
    question_items,
    tarflow.iquizoo::pickup(
      "
SELECT *
FROM iquizoo_content_db.question_items
  "
    )
  )
)
```

```{targets download-recodings, include=FALSE}
list(
  tar_target(
    recordings,
    data_parsed_ERT |>
      pluck("raw_parsed", 1, "detail") |>
      possibly(download_detail)(),
    format = "file",
    pattern = map(data_parsed_ERT)
  )
)
```

```{r run-pipeline, include=FALSE}
tar_make_future(workers = 8)
```

```{r}
library(tidyverse)
library(rvest)
requireNamespace("bit64")
tar_load(users)
tar_load(data_parsed_ERT)
tar_load(data_parsed_PlotR)
tar_load(questions)
tar_load(question_items)
```

```{r}
movie_recollection <- users |>
  inner_join(data_parsed_ERT, by = "user_id") |>
  select(
    user_id, user_name, game_id, game_name, game_time, game_duration, 
    raw_parsed
  ) |>
  mutate(game_duration = game_duration / 60000) |>
  unnest(raw_parsed)
writexl::write_xlsx(movie_recollection, "behav/movie_recollection.xlsx")
```

```{r}
question_names <- questions |>
  select(Id, Name) |>
  deframe()
question_items_names <- question_items |>
  select(Id, ItemTitle) |>
  deframe()
movie_reasoning <- users |>
  inner_join(data_parsed_PlotR, by = "user_id") |>
  unnest(raw_parsed) |>
  select(
    user_id, user_name, game_id, game_name, game_time, game_duration,
    itemid, rt, resp, cresp, acc
  ) |>
  mutate(game_duration = game_duration / 60000) |>
  mutate(
    question_name = question_names[as.character(itemid)] |>
      map_chr(
        ~ read_html(.) |>
          html_text2()
      ),
    .after = itemid,
    .keep = "unused"
  ) |>
  mutate(
    resp = if_else(
      cresp == "",
      resp,
      question_items_names[resp]
    ),
    .keep = "unused"
  )
writexl::write_xlsx(movie_reasoning, "behav/movie_reasoning.xlsx")
```
