---
title: "Pre-processing raw data"
author: Liang Zhang
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(targets)
library(rvest)
requireNamespace("bit64")
tar_load(users)
```

```{r}
#| label: move-recollection

tar_load(data_parsed_ERT)
movie_recollection <- users |>
  inner_join(data_parsed_ERT, by = "user_id") |>
  select(
    user_id, user_name, game_id, game_name, game_time, game_duration, 
    raw_parsed
  ) |>
  mutate(game_duration = game_duration / 60000) |>
  unnest(raw_parsed)
writexl::write_xlsx(movie_recollection, "behav/movie_recollection.xlsx")
```

```{r}
#| label: questionnaire

# question info
question_names <- tar_read(questions) |>
  select(Id, Name)
question_items_names <- tar_read(question_items) |>
  select(Id, ItemTitle) |> 
  filter(Id != 0)

# include all the questionnaires
questionnaires <- bind_rows(
  tar_read(data_parsed_PlotR) |>
    filter(map_lgl(raw_parsed, ~ is.character(.$score))),
  tar_read(data_parsed_LNSQQ),
  tar_read(data_parsed_LMSQQ),
  tar_read(data_parsed_Sleepiness),
  tar_read(data_parsed_SBQ),
  tar_read(data_parsed_STQ)
) |> 
  tidytable::unnest(raw_parsed) |> 
  separate_longer_delim(resp, ",") |> 
  mutate(
    item_id_typed = bit64::as.integer64(itemid),
    resp_typed = bit64::as.integer64(resp)
  ) |> 
  left_join(
    question_names, 
    by = join_by(item_id_typed == Id)
  ) |> 
  left_join(
    question_items_names,
    by = join_by(resp_typed == Id)
  ) |> 
  mutate(
    game_duration = game_duration / 60000,
    question_name = str_extract(Name, "(?<=<p>).+(?=</p>)"),
    resp_text = coalesce(ItemTitle, resp)
  ) |> 
  summarise(
    resp_text = str_c(resp_text, collapse = ";"),
    .by = c(user_id, game_time, game_duration, game_name, question_name, acc)
  ) |> 
  left_join(users, by = "user_id") |> 
  mutate(user_sex = c("M", "F")[user_sex]) |> 
  select(
    user_name, user_sex, user_dob, game_time, game_duration,
    game_name, question_name, resp_text, acc
  )
writexl::write_xlsx(questionnaires, "behav/questionnaires.xlsx")
```

```{r}
#| label: temp-order-judge

tar_read(data_parsed_TMT) |>
  select(user_id, game_time, raw_parsed) |> 
  unnest(raw_parsed) |> 
  writexl::write_xlsx("behav/temporal_order.xlsx")
```
